dist: xenial
language: python
python:
  - "3.7"

jobs:
  include:
    - name: "flake8"
      install:
        - pip install -r requirements.txt
        - pip install flake8
      script:
       - flake8 .
    - name: "unit tests"
      install:
        - pip install -r requirements.txt
      script:
        - python -m test.trainer.test_base_trainer